#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-trojan"
main = "src/index.js"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

[vars]
SHA224PASS = "4bcf61dd0f5231ca72cd747ff858dc301f818eff673d10cd9afbb898"
